version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: ./ms/Dockerfile
    image: rover-api-ms
    expose:
      - "8000"
  web:
    build: ./web
    image: rover-web
    ports:
      - "4001:3000"
